#!/usr/bin/env python3
import json

with open('app/src/main/assets/initial_content.json.backup', 'r') as f:
    guides = json.load(f)

# Descriptions for existing guides
descriptions = {
    "cpr_adult": ("Step-by-step CPR instructions for adults.", "Maelekezo ya hatua kwa hatua ya CPR kwa watu wazima."),
    "cpr_child": ("CPR instructions for children aged 1-8 years.", "Maelekezo ya CPR kwa watoto wa miaka 1-8."),
    "cpr_infant": ("CPR instructions for infants under 1 year.", "Maelekezo ya CPR kwa watoto wachanga chini ya mwaka 1."),
    "choking_adult": ("First aid for a choking adult.", "Huduma ya kwanza kwa mtu mzima anayenasa."),
    "choking_child": ("First aid for a choking child or infant.", "Huduma ya kwanza kwa mtoto au mchanga anayenasa."),
    "heart_attack": ("Signs of a heart attack and immediate actions.", "Dalili za mshtuko wa moyo na hatua za haraka."),
    "stroke": ("Identifying a stroke using FAST and what to do.", "Kutambua kiharusi kwa kutumia FAST na nini cha kufanya."),
    "severe_bleeding": ("How to stop severe bleeding.", "Jinsi ya kuzuia kutokwa na damu sana."),
    "anaphylaxis": ("Emergency treatment for severe allergic reactions.", "Matibabu ya dharura kwa mzio mkubwa."),
    "drowning": ("Rescue and first aid for drowning victims.", "Uokoaji na huduma ya kwanza kwa waliozama."),
    "burns": ("Treatment for minor and major burns.", "Matibabu ya maumivu ya moto madogo na makubwa."),
    "fracture": ("First aid for broken bones.", "Huduma ya kwanza kwa mifupa iliyovunjika."),
    "head_injury": ("Signs of concussion and head injury care.", "Dalili za mtikiso wa ubongo na huduma ya jeraha la kichwa."),
    "poisoning": ("Immediate steps for suspected poisoning.", "Hatua za haraka kwa ushuku wa sumu."),
    "snake_bite": ("What to do (and not do) for a snake bite.", "Nini cha kufanya (na kutofanya) kwa kuumwa na nyoka."),
    "seizure": ("First aid for seizures and epilepsy.", "Huduma ya kwanza kwa kifafa."),
    "shock": ("Treating medical shock.", "Kutibu mshtuko wa kimatibabu."),
    "eye_injury": ("First aid for eye injuries.", "Huduma ya kwanza kwa majeraha ya jicho.")
}

# Update existing guides with descriptions
for guide in guides:
    if guide["id"] in descriptions:
        guide["description_en"] = descriptions[guide["id"]][0]
        guide["description_sw"] = descriptions[guide["id"]][1]
    else:
        guide["description_en"] = "Emergency guide."
        guide["description_sw"] = "Mwongozo wa dharura."

def g(id,en,sw,cat,kw,desc_en,desc_sw,steps):
    return {"id":id,"title_en":en,"title_sw":sw,"icon_asset":f"ic_{cat.lower()}","category":cat,"keywords":kw,"description_en":desc_en,"description_sw":desc_sw,"steps":[{"text_en":s[0],"text_sw":s[1],"audio_asset_en":None,"audio_asset_sw":None,"graphic_asset":None,"timer_seconds":s[2] if len(s)>2 else None} for s in steps]}

# Add 75 more guides (25 existing + 75 = 100 total)
new = [
    g("asthma_severe","Severe Asthma Attack","Shambulio Kali la Pumu","Critical","asthma,breathing,pumu","Emergency steps for severe asthma attack.","Hatua za dharura kwa shambulio kali la pumu.",[("Sit upright, loosen clothing","Keti wima, legeza nguo"),("Use inhaler: 4 puffs","Tumia inhaler: puffs 4"),("Call 999/112 if no improvement","Piga 999/112 kama hakuna maboresho"),("Repeat every 4 min","Rudia kila dakika 4")]),
    g("diabetic_low","Low Blood Sugar","Sukari Chini","Critical","diabetes,sugar,kisukari","Treatment for hypoglycemia (low blood sugar).","Matibabu ya sukari ya chini ya damu.",[("Give sugary drink/food","Toa kinywaji chenye sukari"),("Wait 15 minutes","Subiri dakika 15",900),("Recheck symptoms","Angalia dalili tena"),("Call 999/112 if unconscious","Piga 999/112 kama amepoteza fahamu")]),
    g("seizure_prolonged","Prolonged Seizure","Kifafa Kirefu","Critical","seizure,kifafa","Managing a seizure lasting longer than 5 minutes.","Kudhibiti kifafa kinachodumu zaidi ya dakika 5.",[("Time the seizure","Pima muda",300),("Clear area, protect head","Safisha, linda kichwa"),("Do NOT restrain","USIMSHIKE"),("Call 999/112 if over 5 min","Piga 999/112 kama zaidi ya dakika 5")]),
    g("allergic_severe","Severe Allergic Reaction","Mzio Mkubwa","Critical","allergy,mzio","Immediate actions for anaphylaxis.","Hatua za haraka kwa anaphylaxis.",[("Call 999/112 immediately","Piga 999/112 mara moja"),("Use EpiPen if available","Tumia EpiPen ikipo"),("Lay down, elevate legs","Lala, inua miguu"),("Monitor breathing","Angalia upumuaji")]),
    g("chest_pain","Chest Pain","Maumivu ya Kifua","Critical","chest,heart,kifua","First aid for chest pain and suspected heart attack.","Huduma ya kwanza kwa maumivu ya kifua na ushuku wa mshtuko wa moyo.",[("Call 999/112 immediately","Piga 999/112 mara moja"),("Sit down, rest","Keti, pumzika"),("Give aspirin if available","Toa aspirini ikipo"),("Loosen tight clothing","Legeza nguo")]),
    g("wound_deep","Deep Wound","Jeraha Refu","Urgent","wound,cut,jeraha","Care for deep cuts and severe bleeding.","Huduma kwa majeraha marefu na kutokwa na damu sana.",[("Apply direct pressure","Bonyeza moja kwa moja"),("Elevate if possible","Inua ikiwezekana"),("Do NOT remove objects","USIONDOE vitu"),("Call 999/112 if severe","Piga 999/112 kama kali")]),
    g("burn_minor","Minor Burns","Maumivu Madogo ya Moto","Common","burn,moto","Treatment for first-degree burns.","Matibabu ya maumivu ya moto ya daraja la kwanza.",[("Cool with water 10-20 min","Pooza kwa maji dakika 10-20",600),("Remove jewelry","Toa vito"),("Cover with clean cloth","Funika kitambaa safi"),("Do NOT use ice/butter","USITUMIE barafu/siagi")]),
    g("burn_major","Major Burns","Maumivu Makubwa ya Moto","Critical","burn,fire,moto","Emergency care for severe burns.","Huduma ya dharura kwa maumivu makubwa ya moto.",[("Call 999/112 immediately","Piga 999/112 mara moja"),("Remove from heat","Toa kutoka joto"),("Cool with water if safe","Pooza kama salama"),("Cover with clean sheet","Funika shuka safi")]),
    g("fracture_arm","Arm Fracture","Mkono Kuvunjika","Urgent","fracture,arm,mkono","First aid for a broken arm.","Huduma ya kwanza kwa mkono uliovunjika.",[("Immobilize the arm","Weka mkono imara"),("Apply ice pack","Weka barafu"),("Support with sling","Tegemeza sling"),("Seek medical help","Tafuta msaada")]),
    g("fracture_leg","Leg Fracture","Mguu Kuvunjika","Urgent","fracture,leg,mguu","First aid for a broken leg.","Huduma ya kwanza kwa mguu uliovunjika.",[("Do NOT move person","USIHAMISHE mtu"),("Call 999/112","Piga 999/112"),("Immobilize leg","Weka mguu imara"),("Treat for shock","Tibu mshtuko")]),
    g("fever_management","Fever Management","Kudhibiti Homa","Common","fever,homa","How to manage fever at home.","Jinsi ya kudhibiti homa nyumbani.",[("Give paracetamol","Toa paracetamol"),("Drink plenty fluids","Nywa maji mengi"),("Rest in cool place","Pumzika mahali baridi"),("Seek help if very high","Tafuta msaada kama juu sana")]),
    g("diarrhea_treatment","Diarrhea Treatment","Matibabu ya Kuhara","Common","diarrhea,kuhara","Home treatment for diarrhea.","Matibabu ya nyumbani kwa kuhara.",[("Drink ORS or water","Nywa ORS au maji"),("Continue light foods","Endelea chakula nyepesi"),("Wash hands frequently","Osha mikono mara kwa mara"),("Seek help if severe","Tafuta msaada kama kali")]),
    g("vomiting_treatment","Vomiting Treatment","Matibabu ya Kutapika","Common","vomit,kutapika","Managing vomiting and preventing dehydration.","Kudhibiti kutapika na kuzuia ukosefu wa maji.",[("Stop eating 1-2 hours","Acha kula masaa 1-2"),("Sip water slowly","Nywa maji pole"),("Start bland foods","Anza chakula rahisi"),("Seek help if persistent","Tafuta msaada kama inaendelea")]),
    g("cough_treatment","Cough Treatment","Matibabu ya Kikohozi","Common","cough,kikohozi","Relief for common coughs.","Msaada kwa kikohozi cha kawaida.",[("Drink warm liquids","Nywa vitu vya joto"),("Use honey if over 1 year","Tumia asali zaidi ya mwaka 1"),("Rest and hydrate","Pumzika na maji"),("Seek help if breathing difficulty","Tafuta msaada kama shida kupumua")]),
    g("cold_treatment","Common Cold","Mafua","Common","cold,mafua","Remedies for the common cold.","Dawa za mafua ya kawaida.",[("Rest and drink fluids","Pumzika na maji"),("Use saline nasal drops","Tumia matone pua"),("Paracetamol for pain","Paracetamol kwa maumivu"),("Wash hands often","Osha mikono mara kwa mara")]),
    g("malaria_suspected","Suspected Malaria","Ushuku wa Malaria","Urgent","malaria,homa","What to do if you suspect malaria.","Nini cha kufanya ukishuku malaria.",[("Seek medical help immediately","Tafuta msaada mara moja"),("Note when symptoms started","Kumbuka dalili zilipoanza"),("Keep cool and hydrated","Weka baridi na maji"),("Do NOT self-medicate","USIJITIBIYE")]),
    g("typhoid_suspected","Suspected Typhoid","Ushuku wa Homa ya Matumbo","Urgent","typhoid,homa","Steps to take for suspected typhoid fever.","Hatua za kuchukua kwa ushuku wa homa ya matumbo.",[("Seek medical help urgently","Tafuta msaada haraka"),("Drink clean water only","Nywa maji safi tu"),("Rest completely","Pumzika kabisa"),("Avoid preparing food","Epuka kuandaa chakula")]),
    g("cholera_suspected","Suspected Cholera","Ushuku wa Kipindupindu","Critical","cholera,diarrhea","Immediate actions for suspected cholera.","Hatua za haraka kwa ushuku wa kipindupindu.",[("Call 999/112 immediately","Piga 999/112 mara moja"),("Give ORS frequently","Toa ORS mara kwa mara"),("Isolate patient","Tenga mgonjwa"),("Wash hands with soap","Osha mikono sabuni")]),
    g("pregnancy_bleeding","Pregnancy Bleeding","Kutokwa Damu Ujauzito","Critical","pregnancy,ujauzito","Emergency steps for bleeding during pregnancy.","Hatua za dharura kwa kutokwa na damu wakati wa ujauzito.",[("Call 999/112 immediately","Piga 999/112 mara moja"),("Lie down and rest","Lala na pumzika"),("Do NOT insert anything","USIWEKE kitu"),("Save any tissue","Hifadhi tishu")]),
    g("newborn_jaundice","Newborn Jaundice","Njano Mtoto Mchanga","Urgent","jaundice,njano","Managing mild jaundice in newborns.","Kudhibiti njano nyepesi kwa watoto wachanga.",[("Expose to indirect sunlight","Weka jua la moja kwa moja"),("Feed frequently","Lisha mara kwa mara"),("Monitor skin color","Angalia rangi ngozi"),("Seek help if worsening","Tafuta msaada kama inaongezeka")])
]

# Continue adding more guides to reach 100...
# Adding 55 more comprehensive guides

more_guides = [
    g("headache_severe","Severe Headache","Maumivu Makali ya Kichwa","Urgent","headache,kichwa","Relief for severe headaches.","Msaada kwa maumivu makali ya kichwa.",[("Rest in dark quiet room","Pumzika chumba cha giza"),("Take pain medication","Chukua dawa ya maumivu"),("Apply cold compress","Weka kipooza baridi"),("Seek help if sudden/worst ever","Tafuta msaada kama ghafla/mbaya sana")]),
    g("toothache","Toothache","Maumivu ya Jino","Common","tooth,pain,jino","Home remedies for toothache.","Dawa za nyumbani kwa maumivu ya jino.",[("Rinse with warm salt water","Sukutua maji ya chumvi joto"),("Take pain medication","Chukua dawa ya maumivu"),("Apply cold compress outside","Weka kipooza nje"),("See dentist soon","Ona daktari wa meno haraka")]),
    g("earache","Earache","Maumivu ya Sikio","Common","ear,pain,sikio","Managing ear pain.","Kudhibiti maumivu ya sikio.",[("Do NOT insert anything","USIWEKE kitu"),("Apply warm compress","Weka kipooza cha joto"),("Take pain medication","Chukua dawa ya maumivu"),("See doctor if persists","Ona daktari kama inaendelea")]),
    g("sore_throat_severe","Severe Sore Throat","Maumivu Makali ya Koo","Urgent","throat,koo","Relief for severe sore throat.","Msaada kwa maumivu makali ya koo.",[("Gargle warm salt water","Koroga maji chumvi joto"),("Take pain medication","Chukua dawa ya maumivu"),("Drink warm liquids","Nywa vitu vya joto"),("See doctor if difficulty swallowing","Ona daktari kama shida kumeza")]),
    g("abdominal_pain","Abdominal Pain","Maumivu ya Tumbo","Urgent","abdomen,stomach,tumbo","Assessing and managing abdominal pain.","Kutathmini na kudhibiti maumivu ya tumbo.",[("Note location and type","Kumbuka mahali na aina"),("Avoid eating if severe","Epuka kula kama kali"),("Rest in comfortable position","Pumzika nafasi nzuri"),("Seek help if severe/persistent","Tafuta msaada kama kali/inaendelea")]),
    g("back_pain_acute","Acute Back Pain","Maumivu ya Mgongo Ghafla","Common","back,pain,mgongo","Managing sudden back pain.","Kudhibiti maumivu ya mgongo ya ghafla.",[("Rest but avoid bed rest","Pumzika lakini epuka kulala sana"),("Apply ice first 48 hours","Weka barafu masaa 48 ya kwanza"),("Take pain medication","Chukua dawa ya maumivu"),("Gentle stretching when able","Nyoosha pole unapoweza")]),
    g("neck_pain","Neck Pain","Maumivu ya Shingo","Common","neck,pain,shingo","Relief for neck pain.","Msaada kwa maumivu ya shingo.",[("Rest and avoid sudden movements","Pumzika epuka mwendo wa ghafla"),("Apply ice or heat","Weka barafu au joto"),("Take pain medication","Chukua dawa ya maumivu"),("Seek help if after injury","Tafuta msaada kama baada ya jeraha")]),
    g("muscle_cramp","Muscle Cramp","Mshipa Kusonga","Common","cramp,muscle,mshipa","Relieving muscle cramps.","Kupunguza msongo wa mshipa.",[("Gently stretch the muscle","Nyoosha mshipa pole"),("Massage the area","Kanda eneo"),("Apply heat","Weka joto"),("Drink water and rest","Nywa maji na pumzika")]),
    g("nausea","Nausea","Kichefuchefu","Common","nausea,sick,kichefuchefu","Managing nausea and vomiting.","Kudhibiti kichefuchefu na kutapika.",[("Sit or lie down","Keti au lala"),("Sip clear fluids","Nywa maji safi pole"),("Eat bland foods","Kula chakula rahisi"),("Avoid strong smells","Epuka harufu kali")]),
    g("hiccups","Persistent Hiccups","Kiwete Kinachendelea","Common","hiccups,kiwete","Stopping persistent hiccups.","Kusimamisha kiwete kinachoendelea.",[("Hold breath 10 seconds","Shikilia pumzi sekunde 10"),("Drink water slowly","Nywa maji pole"),("Breathe into paper bag","Pumua kwenye mfuko wa karatasi"),("Seek help if over 48 hours","Tafuta msaada kama zaidi masaa 48")]),
    g("allergic_reaction_mild","Mild Allergic Reaction","Mzio Mdogo","Common","allergy,rash,mzio","Treating mild allergic reactions.","Kutibu mzio mdogo.",[("Stop exposure to allergen","Acha kitu kinachosababisha"),("Take antihistamine","Chukua dawa ya mzio"),("Apply cool compress","Weka kipooza baridi"),("Seek help if worsens","Tafuta msaada kama inaongezeka")]),
    g("rash_general","Skin Rash","Upele wa Ngozi","Common","rash,skin,upele","General care for skin rashes.","Huduma ya jumla kwa upele wa ngozi.",[("Keep area clean and dry","Weka eneo safi na kavu"),("Avoid scratching","Epuka kukuna"),("Apply calamine lotion","Weka lotion ya calamine"),("See doctor if spreads","Ona daktari kama inaenea")]),
    g("sunburn","Sunburn","Kuchomwa na Jua","Common","sun,burn,jua","Relief for sunburn.","Msaada kwa kuchomwa na jua.",[("Cool with water","Pooza kwa maji"),("Apply aloe vera","Weka aloe vera"),("Take pain medication","Chukua dawa ya maumivu"),("Drink extra water","Nywa maji zaidi"),("Avoid sun until healed","Epuka jua hadi ipone")]),
    g("dehydration_mild","Mild Dehydration","Ukosefu Mdogo wa Maji","Common","dehydration,thirst,maji","Rehydrating after mild dehydration.","Kunywa maji baada ya ukosefu mdogo wa maji.",[("Drink water or ORS","Nywa maji au ORS"),("Rest in cool place","Pumzika mahali baridi"),("Avoid caffeine/alcohol","Epuka kahawa/pombe"),("Monitor urine color","Angalia rangi ya mkojo")]),
    g("heat_exhaustion","Heat Exhaustion","Uchovu wa Joto","Urgent","heat,exhaustion,joto","Treating heat exhaustion.","Kutibu uchovu wa joto.",[("Move to cool place","Hamia mahali baridi"),("Drink cool water","Nywa maji baridi"),("Loosen clothing","Legeza nguo"),("Apply cool wet cloths","Weka vitambaa baridi vilivyolowa")]),
    g("frostbite_mild","Mild Frostbite","Baridi Kidogo Kuchoma","Common","cold,frostbite,baridi","First aid for mild frostbite.","Huduma ya kwanza kwa baridi kidogo kuchoma.",[("Move to warm place","Hamia mahali pa joto"),("Warm gradually","Ongeza joto pole pole"),("Do NOT rub area","USIKANDE eneo"),("Seek help if severe","Tafuta msaada kama kali")]),
    g("altitude_sickness","Altitude Sickness","Ugonjwa wa Kimo","Urgent","altitude,mountain,mlima","Managing altitude sickness.","Kudhibiti ugonjwa wa kimo.",[("Descend to lower altitude","Shuka chini"),("Rest and hydrate","Pumzika na maji"),("Take pain medication","Chukua dawa ya maumivu"),("Seek help if severe","Tafuta msaada kama kali")]),
    g("motion_sickness","Motion Sickness","Kichefuchefu cha Usafiri","Common","motion,travel,usafiri","Preventing and treating motion sickness.","Kuzuia na kutibu kichefuchefu cha usafiri.",[("Look at horizon","Angalia upeo"),("Get fresh air","Pata hewa safi"),("Avoid reading","Epuka kusoma"),("Take motion sickness medication","Chukua dawa ya kichefuchefu")]),
    g("hangover","Hangover","Hangover","Common","alcohol,headache,pombe","Recovering from a hangover.","Kupona kutoka hangover.",[("Drink plenty of water","Nywa maji mengi"),("Eat bland foods","Kula chakula rahisi"),("Rest","Pumzika"),("Take pain medication","Chukua dawa ya maumivu")]),
    g("food_allergy","Food Allergy","Mzio wa Chakula","Urgent","food,allergy,chakula","Immediate steps for food allergy.","Hatua za haraka kwa mzio wa chakula.",[("Stop eating the food","Acha kula chakula"),("Take antihistamine","Chukua dawa ya mzio"),("Monitor for worsening","Angalia kama inaongezeka"),("Call 999/112 if breathing difficulty","Piga 999/112 kama shida kupumua")]),
    g("lactose_intolerance","Lactose Intolerance","Kutovumilia Maziwa","Common","milk,stomach,maziwa","Managing lactose intolerance symptoms.","Kudhibiti dalili za kutovumilia maziwa.",[("Avoid dairy products","Epuka bidhaa za maziwa"),("Take lactase enzyme","Chukua enzyme ya lactase"),("Drink water","Nywa maji"),("Symptoms usually resolve in hours","Dalili zinaisha kwa masaa")]),
    g("stomach_cramps","Stomach Cramps","Maumivu ya Tumbo","Common","cramps,stomach,tumbo","Relief for stomach cramps.","Msaada kwa maumivu ya tumbo.",[("Rest in comfortable position","Pumzika nafasi nzuri"),("Apply heat to abdomen","Weka joto tumboni"),("Drink warm liquids","Nywa vitu vya joto"),("Avoid solid food temporarily","Epuka chakula kigumu kwa muda")]),
    g("gas_bloating","Gas and Bloating","Gesi na Kuvimba","Common","gas,bloating,gesi","Relieving gas and bloating.","Kupunguza gesi na kuvimba.",[("Walk around gently","Tembea pole"),("Avoid gas-producing foods","Epuka chakula kinachozalisha gesi"),("Drink peppermint tea","Nywa chai ya peppermint"),("Take over-counter medication","Chukua dawa ya dukani")]),
    g("heartburn","Heartburn","Maumivu ya Moyo","Common","heartburn,chest,moyo","Relief for heartburn/acid reflux.","Msaada kwa maumivu ya moyo/asidi reflux.",[("Sit upright","Keti wima"),("Avoid lying down","Epuka kulala"),("Take antacid","Chukua antacid"),("Avoid trigger foods","Epuka chakula kinachosababisha")]),
    g("menstrual_cramps","Menstrual Cramps","Maumivu ya Hedhi","Common","period,cramps,hedhi","Relief for menstrual cramps.","Msaada kwa maumivu ya hedhi.",[("Apply heat to abdomen","Weka joto tumboni"),("Take pain medication","Chukua dawa ya maumivu"),("Rest","Pumzika"),("Gentle exercise may help","Mazoezi laini yanaweza kusaidia")]),
    g("urinary_pain","Painful Urination","Maumivu Wakati wa Mkojo","Urgent","urine,pain,mkojo","What to do for painful urination.","Nini cha kufanya kwa maumivu wakati wa mkojo.",[("Drink plenty of water","Nywa maji mengi"),("Avoid caffeine/alcohol","Epuka kahawa/pombe"),("Take pain medication","Chukua dawa ya maumivu"),("See doctor soon","Ona daktari haraka")]),
    g("vaginal_discharge","Abnormal Vaginal Discharge","Usaha Usiokuwa wa Kawaida","Urgent","vaginal,discharge,usaha","Managing abnormal vaginal discharge.","Kudhibiti usaha usiokuwa wa kawaida.",[("Keep area clean and dry","Weka eneo safi na kavu"),("Avoid douching","Epuka kusafisha ndani"),("Wear cotton underwear","Vaa nguo za ndani za pamba"),("See doctor for diagnosis","Ona daktari kwa uchunguzi")]),
    g("testicular_pain","Testicular Pain","Maumivu ya Korodani","Urgent","testicular,pain,korodani","Immediate care for testicular pain.","Huduma ya haraka kwa maumivu ya korodani.",[("Support the area","Tegemeza eneo"),("Apply ice pack","Weka barafu"),("Lie down","Lala"),("Seek medical help urgently","Tafuta msaada haraka")]),
    g("hemorrhoids","Hemorrhoids","Buasiri","Common","hemorrhoids,rectal,buasiri","Relief for hemorrhoids.","Msaada kwa buasiri.",[("Sit in warm water","Keti majini ya joto"),("Use hemorrhoid cream","Tumia krimu ya buasiri"),("Avoid straining","Epuka kusukuma"),("Eat high-fiber foods","Kula chakula chenye nyuzi")]),
    g("constipation_severe","Severe Constipation","Kustaafu Kwa Nguvu","Common","constipation,bowel,kustaafu","Relief for severe constipation.","Msaada kwa kustaafu kwa nguvu.",[("Drink plenty of water","Nywa maji mengi"),("Eat high-fiber foods","Kula chakula chenye nyuzi"),("Exercise gently","Fanya mazoezi laini"),("Use laxative if needed","Tumia dawa ya kustaafu ikihitajika")]),
    g("dizziness","Dizziness","Kizunguzungu","Common","dizzy,vertigo,kizunguzungu","Managing dizziness.","Kudhibiti kizunguzungu.",[("Sit or lie down immediately","Keti au lala mara moja"),("Close eyes","Funga macho"),("Drink water","Nywa maji"),("Seek help if persistent","Tafuta msaada kama inaendelea")]),
    g("vertigo","Vertigo","Kizunguzungu Kikubwa","Urgent","vertigo,spinning,kizunguzungu","Managing vertigo (spinning sensation).","Kudhibiti kizunguzungu kikubwa (hisia ya kuzunguka).",[("Lie still","Lala bila kusogea"),("Avoid sudden movements","Epuka mwendo wa ghafla"),("Focus on stationary object","Angalia kitu kisichosogea"),("See doctor for treatment","Ona daktari kwa matibabu")]),
    g("tinnitus","Ringing in Ears","Sauti Sikioni","Common","ringing,ears,sikio","Coping with ringing in the ears.","Kukabiliana na sauti sikioni.",[("Avoid loud noises","Epuka kelele"),("Reduce caffeine","Punguza kahawa"),("Manage stress","Dhibiti msongo"),("See doctor if persistent","Ona daktari kama inaendelea")]),
    g("vision_blurred","Blurred Vision","Kuona Kwa Usikivu","Urgent","vision,eyes,macho","Immediate steps for blurred vision.","Hatua za haraka kwa kuona kwa usikivu.",[("Rest eyes","Pumzisha macho"),("Avoid screens","Epuka skrini"),("Check blood sugar if diabetic","Pima sukari kama una kisukari"),("See doctor if sudden","Ona daktari kama ghafla")]),
    g("dry_eyes","Dry Eyes","Macho Kavu","Common","eyes,dry,macho","Relief for dry eyes.","Msaada kwa macho kavu.",[("Use artificial tears","Tumia machozi bandia"),("Blink frequently","Konyeza mara kwa mara"),("Avoid air conditioning","Epuka AC"),("Take breaks from screens","Pumzika kutoka skrini")]),
    g("red_eyes","Red Eyes","Macho Mekundu","Common","eyes,red,macho","Treating red, irritated eyes.","Kutibu macho mekundu, yaliyokasirika.",[("Rinse with clean water","Osha kwa maji safi"),("Avoid rubbing","Epuka kusugua"),("Use eye drops","Tumia matone ya macho"),("See doctor if painful","Ona daktari kama maumivu")]),
    g("mouth_ulcer","Mouth Ulcer","Kidonda cha Kinywa","Common","mouth,ulcer,kinywa","Treating mouth ulcers.","Kutibu vidonda vya kinywa.",[("Rinse with salt water","Sukutua maji ya chumvi"),("Avoid spicy foods","Epuka chakula chenye pilipili"),("Use oral gel","Tumia jeli ya kinywa"),("Usually heals in 1-2 weeks","Kawaida inapona wiki 1-2")]),
    g("bad_breath","Bad Breath","Harufu Mbaya ya Kinywa","Common","breath,mouth,kinywa","Preventing bad breath.","Kuzuia harufu mbaya ya kinywa.",[("Brush teeth twice daily","Safisha meno mara mbili kwa siku"),("Floss daily","Tumia uzi wa meno kila siku"),("Clean tongue","Safisha ulimi"),("See dentist if persists","Ona daktari wa meno kama inaendelea")]),
    g("bleeding_gums","Bleeding Gums","Ufizi Kutokwa Damu","Common","gums,bleeding,ufizi","Managing bleeding gums.","Kudhibiti ufizi kutokwa damu.",[("Brush gently","Safisha pole"),("Floss carefully","Tumia uzi kwa uangalifu"),("Rinse with salt water","Sukutua maji ya chumvi"),("See dentist","Ona daktari wa meno")]),
    g("wisdom_tooth_pain","Wisdom Tooth Pain","Maumivu ya Jino la Akili","Common","tooth,wisdom,jino","Relief for wisdom tooth pain.","Msaada kwa maumivu ya jino la akili.",[("Rinse with salt water","Sukutua maji ya chumvi"),("Take pain medication","Chukua dawa ya maumivu"),("Apply cold compress","Weka kipooza baridi"),("See dentist","Ona daktari wa meno")]),
    g("nail_infection","Nail Infection","Maambukizi ya Kucha","Common","nail,infection,kucha","Treating nail infections.","Kutibu maambukizi ya kucha.",[("Soak in warm salt water","Tia majini ya chumvi joto"),("Keep clean and dry","Weka safi na kavu"),("Apply antibiotic ointment","Weka malahamu ya antibiotiki"),("See doctor if severe","Ona daktari kama kali")]),
    g("ingrown_toenail","Ingrown Toenail","Kucha Kuingia Ndani","Common","toenail,ingrown,kucha","Home care for ingrown toenails.","Huduma ya nyumbani kwa kucha kuingia ndani.",[("Soak foot in warm water","Tia mguu majini ya joto"),("Lift nail edge gently","Inua ukingo wa kucha pole"),("Apply antibiotic ointment","Weka malahamu ya antibiotiki"),("See doctor if infected","Ona daktari kama imeambukizwa")]),
    g("athletes_foot","Athlete's Foot","Ukungu wa Mguu","Common","foot,fungus,mguu","Treating athlete's foot.","Kutibu ukungu wa mguu.",[("Keep feet clean and dry","Weka miguu safi na kavu"),("Use antifungal cream","Tumia krimu ya kuua kuvu"),("Change socks daily","Badilisha soksi kila siku"),("Wear breathable shoes","Vaa viatu vinavyopita hewa")]),
    g("jock_itch","Jock Itch","Kuwashwa Paja","Common","groin,itch,paja","Treating jock itch.","Kutibu kuwashwa paja.",[("Keep area clean and dry","Weka eneo safi na kavu"),("Use antifungal cream","Tumia krimu ya kuua kuvu"),("Wear loose cotton underwear","Vaa nguo za ndani za pamba"),("Avoid tight clothing","Epuka nguo zinazobana")]),
    g("dandruff","Dandruff","Upele wa Kichwa","Common","scalp,dandruff,kichwa","Managing dandruff.","Kudhibiti upele wa kichwa.",[("Use anti-dandruff shampoo","Tumia shampoo ya upele"),("Wash hair regularly","Osha nywele mara kwa mara"),("Avoid scratching","Epuka kukuna"),("Manage stress","Dhibiti msongo")]),
    g("lice","Head Lice","Chawa","Common","lice,head,chawa","Treating head lice.","Kutibu chawa.",[("Use lice treatment shampoo","Tumia shampoo ya chawa"),("Comb with fine-tooth comb","Kanda kwa kitana chenye meno finyu"),("Wash bedding in hot water","Osha vitanda majini ya moto"),("Check family members","Angalia wanafamilia")]),
    g("scabies","Scabies","Kichocho","Urgent","scabies,itch,kichocho","Treating scabies.","Kutibu kichocho.",[("See doctor for prescription","Ona daktari kwa dawa"),("Apply medication as directed","Tumia dawa kama ilivyoelezwa"),("Wash all clothing/bedding","Osha nguo/vitanda vyote"),("Treat all household members","Tibu wote wa nyumbani")]),
    g("warts","Warts","Mafirimbi","Common","warts,skin,mafirimbi","Treating warts.","Kutibu mafirimbi.",[("Keep area clean","Weka eneo safi"),("Use over-counter treatment","Tumia dawa ya dukani"),("Avoid picking","Epuka kung'oa"),("See doctor if spreading","Ona daktari kama inaenea")]),
    g("acne","Acne","Mabubuu","Common","acne,pimples,mabubuu","Managing acne.","Kudhibiti mabubuu.",[("Wash face twice daily","Osha uso mara mbili kwa siku"),("Avoid touching face","Epuka kugusa uso"),("Use oil-free products","Tumia bidhaa zisizo na mafuta"),("See doctor if severe","Ona daktari kama kali")]),
    g("eczema","Eczema","Eczema","Common","eczema,rash,upele","Managing eczema.","Kudhibiti eczema.",[("Keep skin moisturized","Weka ngozi na unyevu"),("Avoid triggers","Epuka vitu vinavyosababisha"),("Use mild soap","Tumia sabuni laini"),("Apply prescribed cream","Weka krimu iliyoandikwa")]),
    g("psoriasis","Psoriasis","Psoriasis","Chronic","psoriasis,skin,ngozi","Managing psoriasis.","Kudhibiti psoriasis.",[("Keep skin moisturized","Weka ngozi na unyevu"),("Avoid stress","Epuka msongo"),("Use prescribed medication","Tumia dawa iliyoandikwa"),("Get sunlight moderately","Pata jua kwa kiasi")]),
    g("anxiety_attack","Anxiety Attack","Shambulio la Wasiwasi","Common","anxiety,panic,wasiwasi","Coping with an anxiety attack.","Kukabiliana na shambulio la wasiwasi.",[("Breathe slowly and deeply","Pumua pole na kwa kina"),("Focus on present moment","Zingatia wakati wa sasa"),("Use grounding techniques","Tumia mbinu za kutuliza"),("Seek help if frequent","Tafuta msaada kama mara kwa mara")]),
    g("panic_attack","Panic Attack","Shambulio la Hofu","Common","panic,anxiety,hofu","Coping with a panic attack.","Kukabiliana na shambulio la hofu.",[("Breathe slowly","Pumua pole"),("Remind yourself it will pass","Jikumbusha itapita"),("Sit or lie down","Keti au lala"),("Seek professional help","Tafuta msaada wa kitaalamu")]),
    g("insomnia","Insomnia","Kutolala","Common","sleep,insomnia,usingizi","Tips for better sleep.","Vidokezo vya usingizi bora.",[("Maintain regular sleep schedule","Weka ratiba ya kulala"),("Avoid screens before bed","Epuka skrini kabla ya kulala"),("Create relaxing bedtime routine","Unda ratiba ya kutuliza"),("Avoid caffeine after noon","Epuka kahawa baada ya adhuhuri")]),
    g("stress_management","Stress Management","Kudhibiti Msongo","Common","stress,anxiety,msongo","Techniques for managing stress.","Mbinu za kudhibiti msongo.",[("Practice deep breathing","Fanya mazoezi ya kupumua"),("Exercise regularly","Fanya mazoezi mara kwa mara"),("Get adequate sleep","Pata usingizi wa kutosha"),("Talk to someone","Zungumza na mtu")]),
]

guides.extend(new)
guides.extend(more_guides)

print(f"Total guides: {len(guides)}")

with open('app/src/main/assets/initial_content.json','w') as f:
    json.dump(guides,f,indent=2,ensure_ascii=False)
    
print("Successfully created 100 comprehensive medical guides!")
